name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:

    name: Test Python ${{ matrix.python_version }} on ${{ matrix.os }}
    strategy:
      matrix:
        # If you update os/version here, remember to update the if for the
        # artifact upload at the end of this file.
        os: [ubuntu-24.04, windows-2022]
        python_version: ['3.12']
    env:
      PYTHONDEVMODE: 1
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install .[dev,ci]

    - name: Analyze with mypy
      run: |
        python -m mypy

    - name: Check format with Black
      run: |
        python -m ruff format --check

    - name: Test with pytest
      run: |
        python -m pytest

    - name: Build a Wheel
      run: |
        python -m build --wheel 

    # Only allow the upload once. Just pick one OS + Python version combo
    # and let it be. (This will be annoying when we update either :/ )
    - if: matrix.os == 'ubuntu-24.04' && matrix.python_version == '3.12'
      uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: dist/gamatrixcli*-none-any.whl
